spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
validation:
  password:
    pattern:  ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,16}$
